#!/usr/bin/env pwsh
# Migrate a legacy tasks.md into the atomic tasks/ directory structure.
#
# Per Constitution Article IX (Directive 2: Atomic Injunction), a single
# tasks.md file is FORBIDDEN. Task artifacts MUST be a tasks/ directory
# of individual T-XXX-[name].md files.
#
# This migration is conservative: it moves the existing tasks.md into
# tasks/T-001-legacy-migrated.md and creates index.md / traceability.md
# stubs if they do not already exist. The human operator is expected to
# review the migrated file and split it into proper atomic tasks before
# proceeding with /atomicspec.implement.
#
# Usage:
#   .\migrate-legacy-tasks.ps1 -FeatureDir <feature-directory>
#
# Example:
#   .\migrate-legacy-tasks.ps1 -FeatureDir "specs\001-my-feature"

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]
    [string]$FeatureDir
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $FeatureDir -PathType Container)) {
    Write-Error "Not a directory: $FeatureDir"
    exit 1
}

$LegacyTasks  = Join-Path $FeatureDir 'tasks.md'
$TasksDir     = Join-Path $FeatureDir 'tasks'
$Index        = Join-Path $FeatureDir 'index.md'
$Traceability = Join-Path $FeatureDir 'traceability.md'

if (-not (Test-Path $LegacyTasks -PathType Leaf)) {
    Write-Error "No legacy tasks.md at $LegacyTasks. Nothing to migrate."
    exit 1
}

if ((Test-Path $TasksDir -PathType Container) -and
    (Get-ChildItem -Path $TasksDir -ErrorAction SilentlyContinue | Select-Object -First 1)) {
    Write-Error "$TasksDir already exists with content. Refusing to overwrite. Resolve the conflict manually."
    exit 1
}

Write-Output "Migrating legacy tasks.md -> atomic tasks/ directory"
Write-Output "  Feature: $FeatureDir"
Write-Output ""

New-Item -ItemType Directory -Path $TasksDir -Force | Out-Null

$migratedFile = Join-Path $TasksDir 'T-001-legacy-migrated.md'
$header = @"
# T-001: Legacy tasks.md (migrated)

**Status**: NEEDS_REVIEW
**Source**: Migrated from $LegacyTasks
**Action Required**: Split this file into atomic T-XXX-[name].md files per the Atomic Injunction.

---

"@
$original = Get-Content -Path $LegacyTasks -Raw
Set-Content -Path $migratedFile -Value ($header + $original) -NoNewline

$backupPath = Join-Path $FeatureDir 'tasks.md.migrated-backup'
Move-Item -Path $LegacyTasks -Destination $backupPath -Force

if (-not (Test-Path $Index -PathType Leaf)) {
    $indexStub = @"
# Feature Index (stub -- generated by migrate-legacy-tasks.ps1)

> **Action required**: Populate this file as the entry point for the feature.
> See .specify/knowledge/stations/ for the Atomic Traceability Model.

## Tasks

- [T-001-legacy-migrated.md](tasks/T-001-legacy-migrated.md) -- NEEDS_REVIEW
"@
    Set-Content -Path $Index -Value $indexStub
    Write-Output "  + created index.md stub"
}

if (-not (Test-Path $Traceability -PathType Leaf)) {
    $traceStub = @"
# Traceability Matrix (stub -- generated by migrate-legacy-tasks.ps1)

> **Action required**: Populate requirement-to-task mappings after splitting
> T-001-legacy-migrated.md into atomic tasks.

| Requirement | Task(s) | Status       |
| ----------- | ------- | ------------ |
| (pending)   | T-001   | NEEDS_REVIEW |
"@
    Set-Content -Path $Traceability -Value $traceStub
    Write-Output "  + created traceability.md stub"
}

Write-Output ""
Write-Output "Migration complete."
Write-Output ""
Write-Output "  Legacy tasks.md -> $backupPath"
Write-Output "  New atomic file  -> $migratedFile"
Write-Output ""
Write-Output "NEXT STEPS:"
Write-Output "  1. Review $migratedFile"
Write-Output "  2. Split each original task heading into a separate T-XXX-[name].md"
Write-Output "  3. Update index.md and traceability.md accordingly"
Write-Output "  4. Delete the .migrated-backup file when satisfied"
Write-Output "  5. Re-run /atomicspec.implement to proceed"
